// Generated by gencpp from file wall_follower/DriveToTarget.msg
// DO NOT EDIT!


#ifndef WALL_FOLLOWER_MESSAGE_DRIVETOTARGET_H
#define WALL_FOLLOWER_MESSAGE_DRIVETOTARGET_H

#include <ros/service_traits.h>


#include <wall_follower/DriveToTargetRequest.h>
#include <wall_follower/DriveToTargetResponse.h>


namespace wall_follower
{

struct DriveToTarget
{

typedef DriveToTargetRequest Request;
typedef DriveToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveToTarget
} // namespace wall_follower


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wall_follower::DriveToTarget > {
  static const char* value()
  {
    return "c8652349d2a34a90a09475339e2a93d9";
  }

  static const char* value(const ::wall_follower::DriveToTarget&) { return value(); }
};

template<>
struct DataType< ::wall_follower::DriveToTarget > {
  static const char* value()
  {
    return "wall_follower/DriveToTarget";
  }

  static const char* value(const ::wall_follower::DriveToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::wall_follower::DriveToTargetRequest> should match 
// service_traits::MD5Sum< ::wall_follower::DriveToTarget > 
template<>
struct MD5Sum< ::wall_follower::DriveToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wall_follower::DriveToTarget >::value();
  }
  static const char* value(const ::wall_follower::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wall_follower::DriveToTargetRequest> should match 
// service_traits::DataType< ::wall_follower::DriveToTarget > 
template<>
struct DataType< ::wall_follower::DriveToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::wall_follower::DriveToTarget >::value();
  }
  static const char* value(const ::wall_follower::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wall_follower::DriveToTargetResponse> should match 
// service_traits::MD5Sum< ::wall_follower::DriveToTarget > 
template<>
struct MD5Sum< ::wall_follower::DriveToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wall_follower::DriveToTarget >::value();
  }
  static const char* value(const ::wall_follower::DriveToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wall_follower::DriveToTargetResponse> should match 
// service_traits::DataType< ::wall_follower::DriveToTarget > 
template<>
struct DataType< ::wall_follower::DriveToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::wall_follower::DriveToTarget >::value();
  }
  static const char* value(const ::wall_follower::DriveToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WALL_FOLLOWER_MESSAGE_DRIVETOTARGET_H
