// Generated by gencpp from file wall_follower/DriveToTargetResponse.msg
// DO NOT EDIT!


#ifndef WALL_FOLLOWER_MESSAGE_DRIVETOTARGETRESPONSE_H
#define WALL_FOLLOWER_MESSAGE_DRIVETOTARGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wall_follower
{
template <class ContainerAllocator>
struct DriveToTargetResponse_
{
  typedef DriveToTargetResponse_<ContainerAllocator> Type;

  DriveToTargetResponse_()
    : msg_feedback()  {
    }
  DriveToTargetResponse_(const ContainerAllocator& _alloc)
    : msg_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_feedback_type;
  _msg_feedback_type msg_feedback;





  typedef boost::shared_ptr< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DriveToTargetResponse_

typedef ::wall_follower::DriveToTargetResponse_<std::allocator<void> > DriveToTargetResponse;

typedef boost::shared_ptr< ::wall_follower::DriveToTargetResponse > DriveToTargetResponsePtr;
typedef boost::shared_ptr< ::wall_follower::DriveToTargetResponse const> DriveToTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wall_follower::DriveToTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wall_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2897a4bc4d7ca330e430870cfdee7314";
  }

  static const char* value(const ::wall_follower::DriveToTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2897a4bc4d7ca330ULL;
  static const uint64_t static_value2 = 0xe430870cfdee7314ULL;
};

template<class ContainerAllocator>
struct DataType< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wall_follower/DriveToTargetResponse";
  }

  static const char* value(const ::wall_follower::DriveToTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg_feedback\n\
\n\
";
  }

  static const char* value(const ::wall_follower::DriveToTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveToTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wall_follower::DriveToTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wall_follower::DriveToTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg_feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WALL_FOLLOWER_MESSAGE_DRIVETOTARGETRESPONSE_H
